# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - label: "code-name"
        name: "author"
        widget: "select"
        options:
          - { label: "sal", value: "sal" }
          - { label: "john", value: "john" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string' }
      - label: "Categories"
        name: "categories"
        widget: "list"
        summary: '{{fields.categories}}'
        field: {label: Categories, name: categories, widget: string}
      - label: "Tags"
        name: "tags"
        widget: "list"
        summary: '{{fields.tags}}'
        field: {label: Tags, name: tags, widget: string}
      - { label: 'Body', name: 'body', widget: 'markdown' }
